Create nightly-release
edamontology/edamontology pull request #719
Opened 2021-06-09 10:11 UTC by bryan-brancotte

Working example can be tested https://github.com/bryan-brancotte/testing-nightly-release

I added you to this repo so you can see how it behave

2021-06-09 15:21 UTC, matuskalas requested changes
Thanks for the workflow @bryan-brancotte! 👍🏽🙏🏽

But please don't create any automatic (pre-)releases or tags, that would cause a major mess. 😱

Could you please change the workflow this way:  (Could also be in a new PR to keep this for a visible reference)
- rename to **"Publish unstable"**
- run it either daily for now, or better whenever there is a change to `EDAM_dev.owl` in the `main`
- generate the `EDAM_dev.min.json` as you do...
- ...but instead of release make a **bot commit** to **https://github.com/edamontology/edamontology.org**, including `EDAM_dev.owl` and `EDAM_dev.min.json`?

The idea is that we can then enable CD to publish the content of that repo to **https://edamontology.org**. And EDAM Browser can load the "unstable" version from https://github.com/edamontology/edamontology.org.

2021-06-10 01:29 UTC, matuskalas commented
Sorry for a very brief review on-the-run. Now additional info:

First of all, I'm very happy that you started these first steps towards CD @bryan-brancotte 🥇🙌🏽

The reason why we can't use GitHub releases for this is that they are automatically archived on Zenodo (also pre-releases). So it would be a bit like a DoS attack on Zenodo, plus not very useful with so many DOIs (rather against the point of findable, stable archives).

I'm not sure if it's considered a good practice to keep deleting git tags, and recreating them with the same name again.
    ➖ It sounds like going against the idea of tags and in fact doing what branches are for.
    ➕ On the other hand, it would be nice to have a pointer in the repo to the commit which is published as the "latest unstable release". However in case every commit in ` main` (at least every changing `EDAM_dev.owl`) gets "published", this is redundant.

One of the questions that stay is, do we want every change in `main` to be published as an "unstable release", or not? From the point of view of maximum automation, the answer might be yes, **as long as all validations succeed✅** But for now, I'd suggest we don't need to answer this immediately (As there are no downstream applications yet, that would be critically dependent on the unstable releases, we can start with any of the options and refine later.)

Another question, a basic technical one about GitHub Actions: Is it possible to filter so that the workflow runs only if the `EDAM_dev.owl` file is actually changed?

(Not so important: I'm considering whether the "unstable release" files should be renamed to `EDAM_unstable....`. This might make sense especially in case not EVERY commit to `EDAM_dev` is "published". And to make it more obvious to the users what this is. Otherwise it might be an unnecessary complication, and we can anyway add symbolic links to _edamontology.org_ for `EDAM_dev`, `EDAM_unstable`, _whatever etc._)

When it comes to EDAM Browser, I find that having `EDAM_dev|unstable` shown as the default _versus_ having `EDAM(last stable)` as default both make sense. Something to consider... (maybe a well-visible switch between these two, plus more hidden options for older stable versions).

2021-06-17 14:57 UTC, bryan-brancotte commented
Hi @matuskalas , so many points ! I'll try to answer them one after the other

> Thanks for the workflow @bryan-brancotte! 👍🏽🙏🏽

:)

> But please don't create any automatic (pre-)releases or tags, that would cause a major mess. 

I won't that is why I did a test project, and a PR

> Could you please change the workflow this way: (Could also be in a new PR to keep this for a visible reference)
> 
> * rename to **"Publish unstable"**
> * run it either daily for now, or better whenever there is a change to `EDAM_dev.owl` in the `main`
> * generate the `EDAM_dev.min.json` as you do...
> * ...but instead of release make a **bot commit** to **https://github.com/edamontology/edamontology.org**, including `EDAM_dev.owl` and `EDAM_dev.min.json`?

I don't know how to do it, plus committing a file after every commit might make the repo grow very fat.

> 
> The idea is that we can then enable CD to publish the content of that repo to **https://edamontology.org**. And EDAM Browser can load the "unstable" version from https://github.com/edamontology/edamontology.org.

Indeed the goal is to have the unstable version for the browser, there could be alternative such as on-the-fly on-demande conversion.

 
> First of all, I'm very happy that you started these first steps towards CD @bryan-brancotte 🥇🙌🏽

You are welcome, this PR also give an example of how an automatic release for tagged version could be, an equivalent pipeline could be triggered only when tagging a commit with the version number. It is as much as proof of concept than a real PR.

> The reason why we can't use GitHub releases for this is that they are automatically archived on Zenodo (also pre-releases). So it would be a bit like a DoS attack on Zenodo, plus not very useful with so many DOIs (rather against the point of findable, stable archives).

Did not knew, indeed no merging !

> I'm not sure if it's considered a good practice to keep deleting git tags, and recreating them with the same name again.

the tag is latest, so I think it is ok

>     ➖ It sounds like going against the idea of tags and in fact doing what branches are for.

I get your point, but creating a branch latest, and merging main after each commit would be in the end a tag. 

 >    ➕ On the other hand, it would be nice to have a pointer in the repo to the commit which is published as the "latest unstable release". However in case every commit in ` main` (at least every changing `EDAM_dev.owl`) gets "published", this is redundant.

We somehow already have the link to the "latest unstable release" : https://github.com/edamontology/edamontology/raw/main/EDAM_dev.owl


> One of the questions that stay is, do we want every change in `main` to be published as an "unstable release", or not? From the point of view of maximum automation, the answer might be yes, **as long as all validations succeed✅** But for now, I'd suggest we don't need to answer this immediately (As there are no downstream applications yet, that would be critically dependent on the unstable releases, we can start with any of the options and refine later.)

I would go for a yes with validation ok, but only if we need to have other format than owl when releasing the unstable release. If not, then https://github.com/edamontology/edamontology/raw/main/EDAM_dev.owl is enough

> 
> Another question, a basic technical one about GitHub Actions: Is it possible to filter so that the workflow runs only if the `EDAM_dev.owl` file is actually changed?

I would say yes: get commit details, grep on EDAM_dev and see if there is a match.

> 
> (Not so important: I'm considering whether the "unstable release" files should be renamed to `EDAM_unstable....`. This might make sense especially in case not EVERY commit to `EDAM_dev` is "published". And to make it more obvious to the users what this is. Otherwise it might be an unnecessary complication, and we can anyway add symbolic links to _edamontology.org_ for `EDAM_dev`, `EDAM_unstable`, _whatever etc._)

EDAM_unstable is more explicite, but working on a file that is named unstable can be disturbing => I have no opinion.


> When it comes to EDAM Browser, I find that having `EDAM_dev|unstable` shown as the default _versus_ having `EDAM(last stable)` as default both make sense. Something to consider... (maybe a well-visible switch between these two, plus more hidden options for older stable versions).

We are working on it with https://github.com/edamontology/edam-browser/issues/216 I think we will go for latest stable by default

2021-09-30 08:46 UTC, bryan-brancotte commented
The need for releasing a json is not there anymore as we now have https://github.com/edamontology/edam2json-js which read the owl. Also, testing the  owl is done in https://github.com/edamontology/edamontology/blob/main/.github/workflows/tests-edam2json.yml 

Thus closing

2021-09-30 08:46 UTC, closed without merging